name: fooddelivery
description: A food delivery app
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0  # Check for the latest version on pub.dev

  # Add other dependencies here if needed
  # Example: provider: ^6.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Add other development dependencies here if needed
  # Example: flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/chicken-biryani.jpg
    - assets/images/chick.jpg
    - assets/images/Mutton.jpg
    - assets/images/Egg.jpg
    - assets/images/paneer.jpg
    - assets/images/user.webp
# Uncomment this section if you have a `flutter_launcher_icons` configuration
# flutter_icons:
#   android: true
#   ios: true
#   image_path: assets/icon/app_icon.png
